I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 282, in script
    python:
ScriptError: could not find label 'start'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\Programs\Renpy SDK\renpy-7.3.5-sdk\renpy\bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "D:\Programs\Renpy SDK\renpy-7.3.5-sdk\renpy\main.py", line 578, in main
    run(restart)
  File "D:\Programs\Renpy SDK\renpy-7.3.5-sdk\renpy\main.py", line 143, in run
    renpy.execution.run_context(True)
  File "D:\Programs\Renpy SDK\renpy-7.3.5-sdk\renpy\execution.py", line 908, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 282, in script
    python:
  File "D:\Programs\Renpy SDK\renpy-7.3.5-sdk\renpy\script.py", line 898, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'start'.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
 
Sun Nov 15 18:34:56 2020
